INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Game", "Games", 1000000, "08/07/2020", "09/07/2020");

INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);
INSERT INTO users (name, age) VALUES ("Crystal", 45);

INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 3);